const env = import.meta.env;

const envs = {
  SERVER_URL: env.VITE_API_URL,
  FIREBASE: {
    API_KEY: env.VITE_FIREBASE_API_KEY,
    AUTH_DOMAIN: env.VITE_FIREBASE_AUTH_DOMAIN,
    DB_URL: env.VITE_FIREBASE_DB_URL,
    PROJECT_ID: env.VITE_FIREBASE_PROJECT_ID,
    STORAGE_BUCKET: env.VITE_FIREBASE_STORAGE_BUCKET,
    MESSAGING_SENDER_ID: env.VITE_FIREBASE_MESSAGING_SENDER_ID,
    APP_ID: env.VITE_FIREBASE_APP_ID,
    MEASUREMENT_ID: env.VITE_FIREBASE_MEASUREMENT_ID,
  },
};

export { envs };
